name: Build linux editor

# Relevant sources:
# - https://game.ci/

on:
  release:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          
          
      - name: Add Build to Release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          zip -r FAForever.Map.Editor.${{ steps.buildStep.outputs.buildVersion }}.Linux.zip ./Structure
          gh release upload v1.0 FAForever.Map.Editor.${{ steps.buildStep.outputs.buildVersion }}.Linux.zip